{
    seed: 10,    

    # Network Hyperparameters
    hidden_dims: [32, 64, 64],
    learning_rate: 0.001,
    activation: relu, # relu or tanh

    # training
    batch_size: 32,
    buffer_size: 500,
    num_warmup: 50,
    num_sample_last: 75,
    num_episodes_update: 30,
    num_steps_update: 300,
    reward_norm_factor: 100.0,
    time_norm_factor: 100.0,
    max_episodes: 100000,
    epsilon: 0.0,
    epsilon_decay: 0.00001,
    epsilon_min: 0.0,

    eval_every: 100,
    eval_num_episodes: 100,

    # RL parameters
    env_name: LunarLander-v2,

    #Logging and saving
    log_file: NoEpsLifoTestNet10,
    save_updates: 100,

    use_cuda: True,
}
